spring.application.name=api-gateway
server.port=9000

# Actuator
management.endpoints.web.exposure.include=health,info,circuitbreakers
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true

# Resilience4j
resilience4j.circuitbreaker.configs.default.register-health-indicator=true
resilience4j.circuitbreaker.configs.default.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.configs.default.sliding-window-size=8
resilience4j.circuitbreaker.configs.default.failure-rate-threshold=20
resilience4j.circuitbreaker.configs.default.minimum-number-of-calls=4
resilience4j.circuitbreaker.configs.default.wait-duration-in-open-state=5s
resilience4j.circuitbreaker.configs.default.permitted-number-of-calls-in-half-open-state=2
resilience4j.circuitbreaker.configs.default.automatic-transition-from-open-to-half-open-enabled=true


# jwt keycloak uri path
keycloak.jwk-set-uri=http://localhost:8091/realms/het-security-realm/protocol/openid-connect/certs
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8091/realms/het-security-realm

security.excluded.urls=/actuator/**,/v3/api-docs/**,/swagger-ui/**,/swagger-ui.html,/swagger-resources/**,/docs/**

#Open API Collect services to one page
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.urls[0].name=User Service
springdoc.swagger-ui.urls[0].url=/docs/user-service/v3/api-docs
springdoc.swagger-ui.urls[1].name=Device Service
springdoc.swagger-ui.urls[1].url=/docs/device-service/v3/api-docs