spring.application.name=usage-service
server.port=8083

# kafka - Consumer
spring.kafka.bootstrap-servers=localhost:9094
spring.kafka.consumer.group-id=usage-service
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
# Use Spring's JsonDeserializer so incoming JSON payloads are converted to POJOs
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
# Trust packages for JsonDeserializer (adjust to specific packages for security)
spring.kafka.consumer.properties.spring.json.trusted.packages=com.vena.kafka.event,com.vena,*
# If producer sets a __TypeId__ header this mapping helps resolve the target class
spring.kafka.consumer.properties.spring.json.type.mapping=energyUsageEvent:com.vena.kafka.event.EnergyUsageEvent

# Kafka - Producer
spring.kafka.template.default-topic=energy-alerts
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# influxdb
influx.url=http://localhost:8086
influx.token=my-token
influx.org=vena
influx.bucket=usage-bucket

# Fixed encoding for the comment
# I spent 1 hour looking for the error because of this stupid place, I will download an extension that checks for such endpoint or syntax errors
device.service.url=http://localhost:8081/api/v1/devices
user.service.url=http://localhost:8080/api/v1/user

# Actuator Configuration for Prometheus
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=when_authorized
management.metrics.tags.application=${spring.application.name}

